### ISSUE TITLE
The method of diagonal in `band_cal_parallel.py` and the 

### ISSUE THREAD

**Issue by newplay** [QuantumLab-ZY/HamGNN#22]

**Comment by QuantumLab-ZY** [comment]
Hi, I would like to check the parameters in your band_cal_parallel.yaml file.

**Comment by newplay** [comment]
> Hi, I would like to check the parameters in your `band_cal_parallel.yaml` file.

Hi, thanks for your response. Here is my configuration file for `band_cal_parallel.py`:

```yaml
filename: MoS2_WSe2_hetero
structure_name: MoS2_WSe2_hetero
graph_data_path: /home5/zjlin/ML_work/HamGNN/Bilayer_TMD/work_dir/openmx_test/transform_moire_MoS2_WSe2/HamGNN_result/heter_moire/graph/graph_data.npz
hamiltonian_path: /home5/zjlin/ML_work/HamGNN/Bilayer_TMD/work_dir/openmx_test/transform_moire_MoS2_WSe2/HamGNN_result/heter_moire/band/version_0/prediction_hamiltonian.npy # The path to the prediction_hamiltonian.npy file. If null, then the Hamiltonian in graph_data.npz will be used instead.

# If k_path and label are null, the k_path will be set automatically.
k_path: [[0., 0., 0.], [0.5, 0., 0.0], [0.333333, 0.333333, 0.], [0., 0., 0.]] 
label: ['$Gamma$', '$M$', '$K$', '$Gamma$']
nk: 90 # The total number of k points in all k paths
auto_mode: False

nao_max: 26
num_wfns: 10 # Export the wave functions in the interval of [VBM-num_wfn, VBM+num_wfn]
save_dir: /home5/zjlin/ML_work/HamGNN/Bilayer_TMD/work_dir/openmx_test/transform_moire_MoS2_WSe2/HamGNN_result/heter_moire/band
soc_switch: False
Ham_type: openmx # openmx or abacus
```
The `pbs_job.sh` script is as follows:
```sh
#! /bin/bash
#PBS -N HamGNN_hetero_MoS2_WSe2
#PBS -e HamGNN_hetero_MoS2_WSe2.err
#PBS -o HamGNN_hetero_MoS2_WSe2.log
#PBS -V
#PBS -l nodes=1:ppn=32,walltime=9999:00:00

cd $PBS_O_WORKDIR
source activate
conda deactivate
conda activate HamGNN
mpirun -np 32 band_cal_parallel --config band_cal_parallel.yaml
```sh
The POSCAR file is attached:
[POSCAR file](https://github.com/user-attachments/files/16178000/POSCAR_transformed_moire_WSe2_MoS2.txt)

I used the model of MoW(SeS)2_model we discussed before. Because the `graph_data.npz` and `prediction_hamiltonian.npy` files are too large, I assume if you evaluate the model by yourself, you will get the same results.
Best Regards
TzuChing
