### ISSUE TITLE
NotImplementedError in band_cal_parallel when diagonalizing Hamiltonian with SOC=False

### ISSUE THREAD

**Issue by liee2333** [QuantumLab-ZY/HamGNN#51]
Dear YangZhong,
I encountered a NotImplementedError while running band_cal_parallel to diagonalize a Hamiltonian matrix generated by HamGNN for a Si2O4 structure. The error occurs despite having soc_switch: False consistently in all configurations (training, inference, and band calculation). The same workflow works for the carbon example.
**Error Traceback**
```
Traceback (most recent call last):
  File "/share/home/liyuting/anaconda3/envs/band/bin/band_cal_parallel", line 8, in <module>
    sys.exit(main())
  File "/share/home/liyuting/anaconda3/envs/band/lib/python3.9/site-packages/HamTool/band_cal_parallel.py", line 1664, in main
    band_cal_nonsoc()
  File "/share/home/liyuting/anaconda3/envs/band/lib/python3.9/site-packages/HamTool/band_cal_parallel.py", line 605, in band_cal_nonsoc
    raise NotImplementedError
NotImplementedError
```
**Configuration Files**
**band.yam**l (used for diagonalization):
```
filename: Si2O4
graph_data_path: /share/home/liyuting/TEST/DeePH/work_dir/inference/2/OUT.silica/graph_data.npz
hamiltonian_path: /share/home/liyuting/TEST/DeePH/work_dir/inference/2/OUT.silica/pre/version_0/prediction_hamiltonian.npy
k_path: null
label: null
nk: 80
nao_max: 13
num_wfns: 4
save_dir: /share/home/liyuting/TEST/DeePH/work_dir/inference/2/OUT.silica/pre/version_0/pre
soc_switch: False  # Explicitly disabled
spin_colinear: False
Ham_type: abacus
```
**Training/Inference Settings (identical for both):**
```
HamGNN_out:
  ham_only: true
  ham_type: abacus
  nao_max: 13
  add_H0: True
  symmetrize: True
  calculate_band_energy: True
  num_k: 5
  band_num_control: 8
  k_path: null
  soc_switch: False  # Consistently disabled
  nonlinearity_type: gate
  spin_constrained: False
  collinear_spin: False
  minMagneticMoment: 0.5
```
**Additional Context**
The carbon example (with similar SOC=False settings) runs successfully.

All steps (training → inference → Hamiltonian prediction) complete without errors. The issue arises only during band_cal diagonalization.

The error suggests a problem in the non-SOC code path (band_cal_nonsoc), though SOC is explicitly disabled.

Request for Guidance
**Could you help identify:**

Why band_cal fails for Si2O4 despite identical SOC settings to the working carbon example?

Whether there are hidden dependencies (e.g., spin-collinear requirements) for non-SOC systems?

Potential workarounds to resolve the NotImplementedError?

Thank you for your support!

**Key points emphasized:**
Consistency: Highlights that SOC is disabled everywhere.
